# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{has_sunspot_scope}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jos\303\251 Valim", "Sebastian Korfmann"]
  s.date = %q{2010-03-23}
  s.description = %q{Forked from github.com/platformatec/has_scope - Slightly modified to map controller filters to your sunspot search (solr)}
  s.email = %q{korfmann.sebastian@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "init.rb",
     "lib/has_scope.rb"
  ]
  s.homepage = %q{http://github.com/skorfmann/has_scope}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Forked from github.com/platformatec/has_scope - Slightly modified to map controller filters to your sunspot search (solr)}
  s.test_files = [
    "test/has_scope_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

